{% set name = "adf2dms" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/adf2dms-{{ version }}.tar.gz
  sha256: ac5482522563925179e57b0612ade62264f6828622df0f1196879033058a4746

build:
  entry_points:
    - adf2dms = adf2dms.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - crccheck
    - python >={{ python_min }}

test:
  imports:
    - adf2dms
  commands:
    - pip check
    - adf2dms --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dlitz/adf2dms
  summary: Convert Amiga disk images from ADF to DMS (DiskMasher) format
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
